#!/bin/bash

day="$1"
preproc_flags="-P -C -traditional-cpp -nostdinc"

template_rust() {
  [ -x rust/$1 ] && {
    echo "rust/$1 already exists, refusing to overwrite"
    return
  }
  # Add binary crate to Cargo.toml
  python template/new-bincrate.py rust/$1

  # Create binary crate
  cargo new rust/$1

  # Copy main.rs, process parts
  local derive_macros='
    -D__DERIVE_DEBUG__=#[derive(Debug)]
		-D__MACRO_USE__=#[macro_use]
		-D__MACRO_EXPORT__=#[macro_export]'
	cpp $preproc_flags \
		$derive_macros \
		-o rust/$1/src/main.rs template/rust/main.rs
  cpp $preproc_flags \
    $derive_macros \
    -o rust/$1/src/p1.rs template/rust/part.rs
  cpp $preproc_flags \
    $derive_macros \
    -o rust/$1/src/p2.rs template/rust/part.rs
	cpp $preproc_flags \
		$derive_macros \
		-o rust/$1/src/error.rs template/rust/error.rs
}

echo "Creating $1 from Rust template"
template_rust "$1"
